// scripts/inject-env.mjs
// Writes src/environments/environment.ts and environment.prod.ts using
// EmailJS values from process.env so the contact form can call EmailJS
// without committing keys to the repo. Runs automatically before
// `ng build` via the `prebuild` npm hook (locally) and is invoked
// explicitly from the GitHub Actions workflow.
import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const ENV_DIR = join(ROOT, 'src', 'environments');

const publicKey            = process.env.EMAILJS_PUBLIC_KEY            ?? '';
const serviceId            = process.env.EMAILJS_SERVICE_ID            ?? '';
const templateId           = process.env.EMAILJS_TEMPLATE_ID           ?? '';
const autoReplyTemplateId  = process.env.EMAILJS_AUTOREPLY_TEMPLATE_ID ?? '';

const make = (production) =>
  `// AUTO-GENERATED by scripts/inject-env.mjs - do not edit by hand.
export const environment = {
  production: ${production},
  emailjs: {
    publicKey: ${JSON.stringify(publicKey)},
    serviceId: ${JSON.stringify(serviceId)},
    templateId: ${JSON.stringify(templateId)},
    autoReplyTemplateId: ${JSON.stringify(autoReplyTemplateId)}
  }
};
`;

await mkdir(ENV_DIR, { recursive: true });
await writeFile(join(ENV_DIR, 'environment.ts'),      make(false));
await writeFile(join(ENV_DIR, 'environment.prod.ts'), make(true));

const ok = publicKey && serviceId && templateId;
const auto = autoReplyTemplateId ? 'auto-reply ON' : 'auto-reply OFF';
console.log(`inject-env: wrote environment files (${ok ? 'configured' : 'EMPTY - form will be hidden / mailto'}, ${auto})`);
